# fastlane add_plugin sentry

# sentry-cli --auth-token 25165c3e073c41b697e2205da693637dac0f61c125d748c2b9258d88e20d6220 upload-dif --org rosewood --project detecta-connect /Users/kanstantsinbucha/Library/Developer/Xcode/Archives/2022-03-06

lane :upload_symbols do
  download_dsyms(
    username: 'estbyright@icloud.com',
    app_identifier: 'group.detecta.apps.connect'
  )
  sentry_upload_dsym(
    auth_token: '25165c3e073c41b697e2205da693637dac0f61c125d748c2b9258d88e20d6220',
    org_slug: 'rosewood',
    project_slug: 'detecta-connect',
  )
end

lane :upload_bcsm do
  sentry_upload_dif(
    auth_token: '25165c3e073c41b697e2205da693637dac0f61c125d748c2b9258d88e20d6220',
    org_slug: 'rosewood',
    project_slug: 'detecta-connect',
    path: '/Users/kanstantsinbucha/Library/Developer/Xcode/Archives/2022-03-06/DetectaConnect 06-03-2022, 17.30.xcarchive',
   symbol_maps: '/Users/kanstantsinbucha/Library/Developer/Xcode/Archives/2022-03-06/DetectaConnect 06-03-2022, 17.30.xcarchive/BCSymbolMaps'
  )
end