lane :flight do |options|
  app_store_connect_api_key(
    key_id: "4ZSC9LK9FP",
    issuer_id: "69a6de7f-25e3-47e3-e053-5b8c7c11a4d1",
    key_content: options[:apikey],
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )
  if ENV['CI']
    create_keychain(
      name: "build",
      password: "123456",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    sync_code_signing(
      readonly: true,
      type: "appstore",
      keychain_name: "build",
      keychain_password: "123456",
      shallow_clone: true
    )
    sh("security find-certificate -a")
  else
    sync_code_signing(
      type: "appstore",
      readonly: true
    )
  end
  if "tag" != options[:event]
    puts options[:event]
    increment_build_number
    commit_version_bump(message: "Build version bump")
    sh("git push")
  end
  build_app(scheme: "D-Connect",
            workspace: "Client.xcworkspace",
            export_method: "app-store",
            include_bitcode: false)
  upload_to_testflight(
    skip_submission: true,
    skip_waiting_for_build_processing: true
  )
end
lane :reset_build_number do
  increment_build_number(build_number: 1)
end
