lane :testflight do |options|
  app_store_connect_api_key(
    key_id: "4ZSC9LK9FP",
    issuer_id: "69a6de7f-25e3-47e3-e053-5b8c7c11a4d1",
    key_content: options[:apikey],
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )
  if options[:createKeychain] 
    create_keychain(
      name: "build",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
  end
  sync_code_signing(type: "appstore")
  increment_build_number
  build_app(scheme: "D-Connect",
            workspace: "Client.xcworkspace",
            export_method: "app-store",
            include_bitcode: false)
  upload_to_testflight(
    skip_submission: true,
    skip_waiting_for_build_processing: true
  )
end
