name: iOS Deploy Main

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    
jobs:
  build-and-deploy:
    runs-on: macos-12
    
    steps:
    - name: Fastlane Match Install Profile & Certificates
      run: fastlane -v
