name: iOS Deploy Main

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    
jobs:
  build-and-deploy:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - name: Create unlocked keychain for build
        run: |
          security create-keychain -p "" build.keychain
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
      - name: Create .ssh files
        run: |
          echo "${{ secrets.SSH_PUBLIC }}" >> ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PRIVATE }}" >> ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          echo "Host *.github.com\n\tAddKeysToAgent yes\n\tIgnoreUnknown UseKeychain\n\tIdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fastlane send to Testflight
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ""
        run: fastlane testflight apikey:"${{ secrets.APPSTORE_API_PRIVATE_KEY }}"
