name: iOS Deploy Main

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    
jobs:
  build-and-deploy:
    runs-on: macos-12
    timeout-minutes: 1
    
    steps:
    - name: Fastlane send to Testflight
      run: fastlane testflight "${{ secrets.APPSTORE_API_PRIVATE_KEY }}"
