name: iOS TestFlight Main

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    
jobs:
  build-and-deploy:
    name: Build IPA and Send to TestFlight
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Log event
        run: |
          echo "github.event_name: "${{ github.event_name }}
          echo "github.event.action: "${{ github.event.action }}
      - name: Select xCode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Create .ssh files
        run: |
          echo "${{ secrets.SSH_PUBLIC }}" >> ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PRIVATE }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          echo "Host *.github.com\n\tAddKeysToAgent yes\n\tIgnoreUnknown UseKeychain\n\tIdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fastlane send to Testflight (tag)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
        run: fastlane flight apikey:"${{ secrets.APPSTORE_API_PRIVATE_KEY }}" event:tag
      - name: Fastlane send to Testflight (dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
        run: fastlane flight apikey:"${{ secrets.APPSTORE_API_PRIVATE_KEY }}" event:dispatch
