name: iOS - build and test main branch -

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Log event
        run: |
          echo "github.event_name: "${{ github.event_name }}
          echo "github.event.action: "${{ github.event.action }}
      - name: Select xCode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Swift Package
        run: cd ExampleAppMain && xcodebuild -scheme ExampleAppMain  test -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" -quiet
